BookTicket/Models/BiletHole.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookTicket.Models
{
    public class BiletHole
    {
        public int BiletHoleId { get; set; }
        public string BiletStatus { get; set; }

    }
}

BookTicket/Models/Movies.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookTicket.Models
{
    public class Movies
    {
        public int MoviesId { get; set; }
        public string MoviesName { get; set; }
        public string MoviesDirector { get; set; }
        public string MoviesDescription { get; set; }
        public string MoviesSeans { get; set; }
        public bool IsApproved { get; set; }
        public bool IsSliderLogin1 { get; set; }
        public bool IsSliderLogin2 { get; set; }
        public bool IsSliderHome { get; set; }
        public string FilmDate { get; set; }
        public string Image { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public Ticket Ticket { get; set; }
        public string CategoryName { get; set; }

    }
    public class Ticket
    {   [Key]
        public int BiletNumberId { get; set; }
        [Required(ErrorMessage ="Lütfen Yer Seçiniz.")]
        public bool FullorEmpty { get; set; }
        public bool KoltukNo1 { get; set; }
        public bool KoltukNo2 { get; set; }
        public bool KoltukNo3 { get; set; }
        public bool KoltukNo4 { get; set; }
        public bool KoltukNo5 { get; set; }
        public bool KoltukNo6 { get; set; }
        public bool KoltukNo7 { get; set; }
        public bool KoltukNo8 { get; set; }
        public bool KoltukNo9 { get; set; }
        public bool KoltukNo10 { get; set; }
        public bool KoltukNo11 { get; set; }
        public bool KoltukNo12 { get; set; }
        public bool KoltukNo13 { get; set; }
        public bool KoltukNo14 { get; set; }
        public bool KoltukNo15 { get; set; }
        public bool KoltukNo16 { get; set; }
        public bool KoltukNo17 { get; set; }
        public bool KoltukNo18 { get; set; }
        public bool KoltukNo19 { get; set; }
        public bool KoltukNo20 { get; set; }
        public bool KoltukNo21 { get; set; }
        public bool KoltukNo22 { get; set; }
        public bool KoltukNo23 { get; set; }
        public bool KoltukNo24 { get; set; }
        public bool KoltukNo25 { get; set; }
        public bool KoltukNo26 { get; set; }
        public bool KoltukNo27 { get; set; }
        public bool KoltukNo28 { get; set; }
        public bool KoltukNo29 { get; set; }
        public bool KoltukNo30 { get; set; }


    }

}

BookTicket/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BookTicket.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace BookTicket.Controllers
{
    public class HomeController : Controller
    {
        private UserManager<ApplicationUser> userManager;
        private IMoviesRepository moviesRepository;
        private ICategoryRepository categoryRepository;
        private IBiletHoleRepository biletHoleRepository;
        public HomeController(UserManager<ApplicationUser> _userManager, IMoviesRepository _moviesRepository, ICategoryRepository category, IBiletHoleRepository _biletHoleRepository)
        {
            userManager = _userManager;
            moviesRepository = _moviesRepository;
            categoryRepository = category;
            biletHoleRepository = _biletHoleRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MoviesDetails(string title)
        {
            return View(moviesRepository.getByTitle(title));
        }

        public IActionResult Movies()
        {
            return View(moviesRepository.getAll().Where(i => i.CategoryName == "Vizyonda"));
        }
        public IActionResult UpComing()
        {
            return View(moviesRepository.getAll().Where(i => i.CategoryName == "UpComing"));
        }
        public IActionResult UpComing2020()
        {
            return View(moviesRepository.getAll().Where(i => i.CategoryName == "UpComing2020"));
        }
        [Authorize]
        public IActionResult BiletHole()
        {
            ViewBag.BiletHole = new SelectList(biletHoleRepository.getAll(), "BiletNumberId");

            return View(biletHoleRepository.getAll());
        }
        [HttpPost]
        public IActionResult TicketStatus(int BiletNumberId, Ticket biletHole)
        {
            if (ModelState.IsValid)
            {

            var user = biletHoleRepository.getAll().Where(i => i.BiletNumberId == BiletNumberId);
            /* user=>biletnumberId = 16 */
            biletHole.FullorEmpty = true;
            biletHoleRepository.UpdateCategory(biletHole);
            return RedirectToAction("BiletHole");
            }
            return RedirectToAction("BiletHole",biletHole);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookTicket/ViewComponents/SliderFirstSliderViewComponent.cs
using BookTicket.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookTicket.ViewComponents
{
    public class SliderFirstSliderViewComponent : ViewComponent
    {
        private IMoviesRepository moviesRepository;

        public SliderFirstSliderViewComponent(IMoviesRepository _moviesRepository)
        {
            moviesRepository = _moviesRepository;
        }
        public IViewComponentResult Invoke()
        {
            return View(moviesRepository.getAll().Where(i=>i.IsSliderLogin1));
        }
    }
}

BookTicket/Views/Home/BiletHole.cshtml
@model IEnumerable<Ticket>

@{
    ViewData["Title"] = "BiletHole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section sections{

    <script>

        $(".userfree").click(function () {
            
            $(this).toggleClass("userfree");
            $(this).toggleClass("userchoose");
            $("#price").toggleClass("d-none");
            $("#price").toggleClass("d-inline");
            if ($(this).hasClass("userchoose")) {
                $("#submit").removeClass("btn-danger");
                $("#submit").removeClass("disabled");
                $("#submit").addClass("btn-primary");
                $("#submit").val("Bilet Seçtiniz");

                if ($(".ticket").hasClass("userchoose")) {
                    var result = $(this).val();
                    $("#submit").val(result);
                }
                else {
                    console.log("seçili eleman yok!")
                }
               
               
            }
            else {
                $("#submit").addClass("btn-danger");
                $("#submit").addClass("disabled");
                $("#submit").removeClass("btn-primary");
            }
            
        })

     
    </script>
}


<div class="container">
    <div class="row">
        <div class="col-12 col-md-4">
            @await Component.InvokeAsync("SliderFirstSlider")
        </div>
        <div class="col-12 col-md-4">
            <div class="text-center"> <span class="userchoose mx-2"> Seçili Koltuk</span> <span class="userfull mx-2">Dolu Koltuk</span> <br /> <span class=" userfree mx-2"> Boş Koltuk</span></div>

            <div class="text-danger text-center"><strong>* 1 Bilet Seçiniz.</strong></div>
            @if (User.Identity.IsAuthenticated)
            {
            <div class="text-center"><strong class="text-success mt-3 mx-5">Hoşgeldiniz, @User.Identity.Name</strong> <br /></div> 
            }
            else
            {


            }


            @foreach (var item in Model)
            {
                @if (item.FullorEmpty == false)
                {
                    <button value="@item.BiletNumberId" name="@item.BiletNumberId" id="ticket" class="userfree ticket bg-transparent border-0"></button>
                    <input type="hidden" class="ticket2" name="" value="@item.BiletNumberId" />
                }
                else
                {
                    <span class="userfull"></span>

                }

            }





            <form asp-action="TicketStatus" method="post">

                <div asp-validation-summary="All" class="mt-3"></div>


                <button class="btn btn-danger disabled mt-5 w-100" value="" name="BiletNumberId" id="submit">Bilet Satın Al</button>


            </form>


        </div>


        
        <div class="col-12 col-md-4 mt-5 ">
            <div class="d-none mt-5" id="price">
                <strong> Bilet Fiyatı : 14TL</strong>

            </div>
        </div>
       

    </div>
</div>
<div class="user"></div>

BookTicket/Views/Home/Movies.cshtml
@model IEnumerable<Movies>
@{
    ViewData["Title"] = "Movies";
}


<div class="container">
 
  
    <div class="row text-center">
        <div class="col-1 d-inline d-md-none"></div>

        <div class="col-10 col-md-4 col-lg-3 mt-5  ">
            <a asp-action="MoviesDetails" asp-controller="Home" asp-route-title="Leon">
                <div class="card bg-transparent text-light border-primary" style="width: 17rem">
                    <img src="~/img/Leon.jpg" class="card-img-top" alt="...">
                    <div class="card-body ">
                        <h5 class="card-title ">Leon</h5>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-1 d-inline d-md-none"></div>
        @foreach (var item in Model)
        {


            <div class="col-1 d-inline d-md-none"></div>
            <div class="col-10 col-md-4 col-lg-3 mt-5  ">
                <a asp-action="MoviesDetails" asp-controller="Home" asp-route-title="@item.MoviesName">
                    <div class="card bg-transparent text-light border-primary" style="width: 17rem">
                        <img src="~/img/@item.Image" class="card-img-top" alt="...">
                        <div class="card-body ">
                            <h5 class="card-title ">@item.MoviesName</h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-1 d-inline d-md-none"></div>
        }




    </div>

</div>

BookTicket/Views/Home/MoviesDetails.cshtml
@model Movies
@{
    ViewData["Title"] = "MoviesDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container mt-5" >
    <div class="row">
        <div class="col-12 col-md-4">
            <img src="~/img/@Model.Image" class="w-100 rounded" alt="Alternate Text" />
        </div>
        <div class="col-12 col-md-8">
            <div class="form-group">
                <p>Yönetmen : <strong>@Model.MoviesDirector</strong></p>
                <p>Vizyon Tarihi : <strong>@Model.FilmDate</strong></p>
                <p>Film Seansları : <strong>@Model.MoviesSeans</strong></p>
                <p> <a asp-action="BiletHole" asp-controller="Home" asp-route-title="@Model.MoviesName" class="btn btn-warning">Biletini Al</a></p>
                <p class=" bg-darktrans p-2 rounded text-justify"> <strong> Film Özeti :</strong>        @Model.MoviesDescription</p>
            </div>
        </div>
    </div>
    
</div>

BookTicket/Views/Home/UpComing.cshtml
@model IEnumerable<Movies>
@{
    ViewData["Title"] = "Movies";
}


<div class="container">


    <div class="row text-center">
     
        @foreach (var item in Model)
        {


            <div class="col-1 d-inline d-md-none"></div>
            <div class="col-10 col-md-4 col-lg-3 mt-5  ">
                <a asp-action="MoviesDetails" asp-controller="Home" asp-route-title="@item.MoviesName">
                    <div class="card bg-transparent text-light border-primary" style="width: 17rem">
                        <img src="~/img/@item.Image" class="card-img-top" alt="...">
                        <div class="card-body ">
                            <h5 class="card-title ">@item.MoviesName</h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-1 d-inline d-md-none"></div>
        }




    </div>

</div>

BookTicket/Views/Home/UpComing2020.cshtml
@model IEnumerable<Movies>
@{
    ViewData["Title"] = "Movies";
}


<div class="container">


    <div class="row text-center">

        @foreach (var item in Model)
        {


            <div class="col-1 d-inline d-md-none"></div>
            <div class="col-10 col-md-4 col-lg-3 mt-5  ">
                <a asp-action="MoviesDetails" asp-controller="Home" asp-route-title="@item.MoviesName">
                    <div class="card bg-transparent text-light border-primary" style="width: 17rem">
                        <img src="~/img/@item.Image" class="card-img-top" alt="...">
                        <div class="card-body ">
                            <h5 class="card-title ">@item.MoviesName</h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-1 d-inline d-md-none"></div>
        }




    </div>

</div>