BookTicket/Models/Movies.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookTicket.Models
{
    public class Movies
    {
        public int MoviesId { get; set; }
        public string MoviesName { get; set; }
        public string MoviesDirector { get; set; }
        public string MoviesDescription { get; set; }
        public string MoviesSeans { get; set; }
        public bool IsApproved { get; set; }
        public bool IsSliderLogin1 { get; set; }
        public bool IsSliderLogin2 { get; set; }
        public bool IsSliderHome { get; set; }
        public string FilmDate { get; set; }
        public string Image { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public Ticket Ticket { get; set; }
        public string CategoryName { get; set; }

    }
    public class Ticket
    {   [Key]
        public int BiletNumberId { get; set; }
        [Required(ErrorMessage ="Lütfen Yer Seçiniz.")]
        public bool FullorEmpty { get; set; }
        public bool KoltukNo1 { get; set; }
        public bool KoltukNo2 { get; set; }
        public bool KoltukNo3 { get; set; }
        public bool KoltukNo4 { get; set; }
        public bool KoltukNo5 { get; set; }
        public bool KoltukNo6 { get; set; }
        public bool KoltukNo7 { get; set; }
        public bool KoltukNo8 { get; set; }
        public bool KoltukNo9 { get; set; }
        public bool KoltukNo10 { get; set; }
        public bool KoltukNo11 { get; set; }
        public bool KoltukNo12 { get; set; }
        public bool KoltukNo13 { get; set; }
        public bool KoltukNo14 { get; set; }
        public bool KoltukNo15 { get; set; }
        public bool KoltukNo16 { get; set; }
        public bool KoltukNo17 { get; set; }
        public bool KoltukNo18 { get; set; }
        public bool KoltukNo19 { get; set; }
        public bool KoltukNo20 { get; set; }
        public bool KoltukNo21 { get; set; }
        public bool KoltukNo22 { get; set; }
        public bool KoltukNo23 { get; set; }
        public bool KoltukNo24 { get; set; }
        public bool KoltukNo25 { get; set; }
        public bool KoltukNo26 { get; set; }
        public bool KoltukNo27 { get; set; }
        public bool KoltukNo28 { get; set; }
        public bool KoltukNo29 { get; set; }
        public bool KoltukNo30 { get; set; }


    }

}

BookTicket/Controllers/TicketAdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BookTicket.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookTicket.Controllers
{ 
    [Authorize]
    public class TicketAdminController : Controller
    {
        private UserManager<ApplicationUser> userManager;
        private IMoviesRepository moviesRepository;
        private ICategoryRepository categoryRepository;
        public TicketAdminController(UserManager<ApplicationUser> _userManager,IMoviesRepository _moviesRepository,ICategoryRepository category)
        {
            userManager = _userManager;
            moviesRepository = _moviesRepository;
            categoryRepository = category;
        }


        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AllMovies()
        {
            return View(moviesRepository.getAll());
        }
        public IActionResult Movies()
        {
            return View(moviesRepository.getAll().Where(i=>i.CategoryName=="Vizyonda"));
        }
        public IActionResult UpComing()
        {
            return View(moviesRepository.getAll().Where(i=>i.CategoryName=="UpComing"));
        }
        public IActionResult UpComing2020()
        {
            return View(moviesRepository.getAll().Where(i=>i.CategoryName=="UpComing2020"));
        }
        public IActionResult Slider()
        {
            return View(moviesRepository.getAll().Where(i=>i.IsSliderLogin1 || i.IsSliderLogin2 || i.IsSliderHome));
        }
        public IActionResult UserList()
        {
            return View(userManager.Users);
        }

        [HttpGet]
        public IActionResult MoviesCreate()
        {
            ViewBag.Categories = new SelectList(categoryRepository.getAll(), "CategoryId", "CategoryName");
            return View();
        }
        [HttpPost]
        public  IActionResult MoviesCreate(Movies movies)
        {


       
            if (ModelState.IsValid)
            {
                moviesRepository.CreateMovies(movies);
                return RedirectToAction("AllMovies");
            }
            return View(movies);
        }
        [HttpPost]
        public IActionResult MoviesDelete(int id)
        {
            moviesRepository.DeleteMovies(id);
            return RedirectToAction("Index");

        }
        public IActionResult MoviesUpdate(int id)
        {
            ViewBag.Categories = new SelectList(categoryRepository.getAll(), "CategoryId", "CategoryName");
            return View(moviesRepository.getById(id));
        }
        [HttpPost]
        public async Task<IActionResult> MoviesUpdate(Movies blog, IFormFile file)
        {

            
            if (ModelState.IsValid)
            {

                if (file != null)
                {


                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }

                    blog.Image = file.FileName;
                }
                moviesRepository.UpdateMovies(blog);
                return RedirectToAction("Index");

            }

            return RedirectToAction("Index");
        }
    }
}

BookTicket/Views/TicketAdmin/AllMovies.cshtml
@model IEnumerable<Movies>
@{
    ViewData["Title"] = "Movies";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@if (Model.Count() == 0)
{
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-3 "></div>
            <div class="col-12 col-md-6 ">
                <p> Vizyonda Bir Film Bulunmamaktadır. </p>
                <p class="text-center">  <a asp-action="MoviesCreate" asp-controller="TicketAdmin" class="btn btn-warning">Yeni bir film oluştur</a>  </p>
            </div>
            <div class="col-12 col-md-3 "></div>
        </div>
    </div>
}
else
{



    <table class="p-1 m-1 table table-bordered table-striped">
        <thead>
            <tr>
                <th>Image</th>
                <th>Film Adı</th>
                <th>Film Yönetmeni</th>
                <th>Durumu</th>
                <th>İşlemler</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Image</td>
                    <td>@item.MoviesName</td>
                    <td>@item.MoviesDirector</td>
                    <td>@item.CategoryName</td>
                    <td>
                        <a asp-action="MoviesDelete" asp-controller="TicketAdmin" asp-route-id="@item.MoviesId" class="btn btn-danger">Delete</a>
                        <a asp-action="MoviesUpdate" asp-controller="TicketAdmin" asp-route-id="@item.MoviesId" class="btn btn-info">Update</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>


    <div class="text-right"> <a asp-action="MoviesCreate" asp-controller="TicketAdmin" class="btn btn-warning">Yeni bir film oluştur</a></div>



}

BookTicket/Views/TicketAdmin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>

BookTicket/Views/TicketAdmin/Movies.cshtml
@model IEnumerable<Movies>
@{
    ViewData["Title"] = "Movies";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@if (Model.Count() == 0)
{
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-3 "></div>
            <div class="col-12 col-md-6 ">
                <p> Vizyonda Bir Film Bulunmamaktadır. </p>
                <p class="text-center">  <a asp-action="MoviesCreate" asp-controller="TicketAdmin" class="btn btn-warning">Yeni bir film oluştur</a>  </p>
            </div>
            <div class="col-12 col-md-3 "></div>
        </div>
    </div>
}
else
{



    <table class="p-1 m-1 table table-bordered table-striped">
        <thead>
            <tr>
                <th>Image</th>
                <th>Film Adı</th>
                <th>Film Yönetmeni</th>
                <th>Durumu</th>
                <th>İşlemler</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
            <tr>
                <td>
                    <img src="~/img/@item.Image" width="120" alt="Alternate Text" />
                </td>
                <td>@item.MoviesName</td>
                <td>@item.MoviesDirector</td>
                <td>@item.CategoryName</td>
                <td>
                    <form asp-action="MoviesDelete" method="post">

                        <button asp-action="MoviesDelete" asp-route-id="@item.MoviesId" class="btn btn-danger">Delete</button>
                    </form>
                    <a asp-action="MoviesUpdate" asp-controller="TicketAdmin" asp-route-id="@item.MoviesId" class="btn btn-info">Update</a>
                </td>

            </tr>
            }
        </tbody>
    </table>


    <div class="text-right"> <a asp-action="MoviesCreate" asp-controller="TicketAdmin" class="btn btn-warning">Yeni bir film oluştur</a></div>



}

BookTicket/Views/TicketAdmin/MoviesCreate.cshtml
@model Movies
@{
    ViewData["Title"] = "MoviesCreate";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



<div class="container">
    <div class="row">
        <div class="col-12 col-md-4"></div>       
        <div class="col-12 col-md-4">
            <form asp-action="MoviesCreate" method="post" enctype="multipart/form-data">

                <div class="form-group">
                    <label asp-for="MoviesName"> Film Adı </label>
                    <input asp-for="MoviesName" class="form-control" />
                </div>

                <div class="form-group">
                    <label asp-for="MoviesDirector"> Film Yönetmeni </label>
                    <input asp-for="MoviesDirector" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="MoviesSeans"> Film Seansları </label>
                    <input asp-for="MoviesSeans" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="MoviesDescription"> Film İçeriği </label>
                    <input asp-for="MoviesDescription" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="CategoryName"> Film Özelliği </label>
                    <select asp-for="CategoryName">
                        <option value="" disabled selected>Seçiniz..</option>
                        <option value="Vizyonda">Vizyonda</option>
                        <option value="UpComing">Yakın Tarihte Vizyona Girecek.</option>
                        <option value="UpComing2020">2020 Yılında Vizyona Girecek.</option>
                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="CategoryId">Category</label>
                    <select class="form-control" asp-for="CategoryId" asp-items="ViewBag.Categories">
                        <option disabled selected value="">Seçiniz</option>

                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="FilmDate"> Film Vizyon Tarihi </label>
                    <input asp-for="FilmDate" class="form-control" />
                </div>
                <div>
                 
                    <input type="text" disabled value="Image kısmı onaylandıktan sonra ekle!" class="form-control" />
                </div>

                <input type="submit" value="Film Oluştur" class="form-control" />
            </form>


        </div>
        <div class="col-12 col-md-4"></div>
    </div>
</div>

BookTicket/Views/TicketAdmin/MoviesUpdate.cshtml
@model Movies
@{
    ViewData["Title"] = "Update to Movie";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



<div class="container">
    <div class="row">
        <div class="col-12 col-md-4"></div>
        <div class="col-12 col-md-4">
            <form asp-action="MoviesUpdate" method="post" enctype="multipart/form-data">

                <input type="hidden" name="MoviesId" value="@Model.MoviesId" />

                <div class="form-group">
                    <label asp-for="MoviesName"> Film Adı </label>
                    <input asp-for="MoviesName" class="form-control" />
                </div>

                <div class="form-group">
                    <label asp-for="MoviesDirector"> Film Yönetmeni </label>
                    <input asp-for="MoviesDirector" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="MoviesSeans"> Film Seansları </label>
                    <input asp-for="MoviesSeans" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="MoviesDescription"> Film İçeriği </label>
                    <input asp-for="MoviesDescription" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="CategoryName"> Film Özelliği </label>
                    <select asp-for="CategoryName" class="form-control">
                        <option value="" disabled selected>Seçiniz..</option>
                        <option value="Vizyonda">Vizyonda</option>
                        <option value="UpComing">Yakın Tarihte Vizyona Girecek.</option>
                        <option value="UpComing2020">2020 Yılında Vizyona Girecek.</option>
                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="CategoryId">Category</label>
                    <select class="form-control" asp-for="CategoryId" asp-items="ViewBag.Categories">
                        <option disabled selected value="">Seçiniz</option>

                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="FilmDate"> Film Vizyon Tarihi </label>
                    <input asp-for="FilmDate" class="form-control" />
                </div>
                
                <div class="form-check mt-2">
                    <label class="form-check-label">
                        <input asp-for="IsApproved" class="form-check-input" />
                        Onayla
                    </label>

                </div>


                <div>
                    <img src="~/img/@Model.Image" width="120" alt="Alternate Text" />
                    <input type="file" name="file" id="file" class="form-control" />
                </div>

                <div class="form-check mt-2">
                    <label class="form-check-label">
                        <input asp-for="IsSliderHome" class="form-check-input" />
                        Ana Sayfa'da Slider Olarak Eklensin mi?
                    </label>

                </div>



                <div class="form-check mt-2">
                    <label class="form-check-label">
                        <input asp-for="IsSliderLogin1" class="form-check-input" />
                        Login&Register  1.Slidera Eklensin mi?
                    </label>
                </div>
                <div class="form-check mt-2">
                    <label class="form-check-label">
                        <input asp-for="IsSliderLogin2" class="form-check-input" />
                        Login&Register 2.Slidera Eklensin mi?
                    </label>

                </div>


                <input type="submit" value="Film Oluştur" class="form-control" />
            </form>


        </div>
        <div class="col-12 col-md-4"></div>
    </div>
</div>

BookTicket/Views/TicketAdmin/Slider.cshtml
@model IEnumerable<Movies>
@{
    ViewData["Title"] = "Movies";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@if (Model.Count() == 0)
{
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-3 "></div>
            <div class="col-12 col-md-6 ">
                <p> Slider'da Bir Film Bulunmamaktadır. </p>
                <p class="text-center">  <a asp-action="MoviesCreate" asp-controller="TicketAdmin" class="btn btn-warning">Yeni bir film oluştur</a>  </p>
            </div>
            <div class="col-12 col-md-3 "></div>
        </div>
    </div>
}
else
{


    <table class="p-1 m-1 table table-bordered table-striped">
        <thead>
            <tr>
                <th>Image</th>
                <th>Film Adı</th>
                <th>Film Yönetmeni</th>
                <th>Durumu</th>
                <th>İşlemler</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
            <tr>
                <td>
                    <img src="~/img/@item.Image" width="120" alt="Alternate Text" />
                </td>
                <td>@item.MoviesName</td>
                <td>@item.MoviesDirector</td>
                <td>@item.CategoryName</td>
                <td>
                    @if (item.IsSliderHome == true)
                    {
                        <p>Ana Sayfada kullanılıyor.</p>
                    }
                    else if (item.IsSliderLogin1 && item.IsSliderLogin2)
                    {
                        <p>Login & Register 1.Slayt'da kullanılıyor.</p>
                        <p>Login & Register 2.Slayt'da kullanılıyor.</p>
                    }
                    else if (item.IsSliderLogin1)
                    {
                        <p>Login & Register 1.Slayt'da kullanılıyor.</p>
                    }
                    else if (item.IsSliderLogin2)
                    {
                        <p>Login & Register 2.Slayt'da kullanılıyor.</p>
                    }

                </td>
                <td>
                    <a asp-action="MoviesDelete" asp-controller="TicketAdmin" asp-route-id="@item.MoviesId" class="btn btn-danger">Delete</a>
                    <a asp-action="MoviesUpdate" asp-controller="TicketAdmin" asp-route-id="@item.MoviesId" class="btn btn-info">Update</a>
                </td>

            </tr>
            }
        </tbody>
    </table>


    <div class="text-right"> <a asp-action="MoviesCreate" asp-controller="TicketAdmin" class="btn btn-warning">Yeni bir film oluştur</a></div>

}

BookTicket/Views/TicketAdmin/UpComing.cshtml
@model IEnumerable<Movies>
@{
    ViewData["Title"] = "Movies";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@if (Model.Count() == 0)
{
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-3 "></div>
            <div class="col-12 col-md-6 ">
                <p> Yakın Tarihte Vizyona Girecek Bir Film Bulunmamaktadır. </p>
                <p class="text-center">  <a asp-action="MoviesCreate" asp-controller="TicketAdmin" class="btn btn-warning">Yeni bir film oluştur</a>  </p>
            </div>
            <div class="col-12 col-md-3 "></div>
        </div>
    </div>
}
else
{


    <table class="p-1 m-1 table table-bordered table-striped">
        <thead>
            <tr>
                <th>Image</th>
                <th>Film Adı</th>
                <th>Film Yönetmeni</th>
                <th>Durumu</th>
                <th>İşlemler</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
            <tr>
                <td>
                    <img src="~/img/@item.Image" width="120" alt="Alternate Text" />
                </td>
                <td>@item.MoviesName</td>
                <td>@item.MoviesDirector</td>
                <td>@item.CategoryName</td>
                <td>
                    <a asp-action="MoviesDelete" asp-controller="TicketAdmin" asp-route-id="@item.MoviesId" class="btn btn-danger">Delete</a>
                    <a asp-action="MoviesUpdate" asp-controller="TicketAdmin" asp-route-id="@item.MoviesId" class="btn btn-info">Update</a>
                </td>

            </tr>
            }
        </tbody>
    </table>


    <div class="text-right"> <a asp-action="MoviesCreate" asp-controller="TicketAdmin" class="btn btn-warning">Yeni bir film oluştur</a></div>
}

BookTicket/Views/TicketAdmin/UpComing2020.cshtml
@model IEnumerable<Movies>
@{
    ViewData["Title"] = "Movies";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@if (Model.Count() == 0)
{
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-3 "></div>
            <div class="col-12 col-md-6 ">
                <p> 2020'de Vizyona girecek Bir Film Bulunmamaktadır. </p>
                <p class="text-center">  <a asp-action="MoviesCreate" asp-controller="TicketAdmin" class="btn btn-warning">Yeni bir film oluştur</a>  </p>
            </div>
            <div class="col-12 col-md-3 "></div>
        </div>
    </div>
}
else
{


    <table class="p-1 m-1 table table-bordered table-striped">
        <thead>
            <tr>
                <th>Image</th>
                <th>Film Adı</th>
                <th>Film Yönetmeni</th>
                <th>Durumu</th>
                <th>İşlemler</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
            <tr>
                <td>
                    <img src="~/img/@item.Image" width="120" alt="Alternate Text" />
                </td>
                <td>@item.MoviesName</td>
                <td>@item.MoviesDirector</td>
                <td>@item.CategoryName</td>
                <td><a asp-action="MoviesDelete" asp-controller="TicketAdmin" asp-route-id="@item.MoviesId" class="btn btn-danger">Delete</a>
                    <a asp-action="MoviesUpdate" asp-controller="TicketAdmin" asp-route-id="@item.MoviesId" class="btn btn-info">Update</a>
                </td>

            </tr>
            }
        </tbody>
    </table>


    <div class="text-right"> <a asp-action="MoviesCreate" asp-controller="TicketAdmin" class="btn btn-warning">Yeni bir film oluştur</a></div>

}

BookTicket/Views/TicketAdmin/UserCreate.cshtml
@{
    ViewData["Title"] = "UserCreate";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>UserCreate</h2>

BookTicket/Views/TicketAdmin/UserList.cshtml
@model IEnumerable<ApplicationUser>
@{
    ViewData["Title"] = "UserList";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<table class="table table-bordered table-striped" >
    <thead>
        <tr>
            <th>User Id</th>
            <th>User Name</th>
            <th>User Email</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.UserName</td>
                <td>@item.Email</td>
            </tr>
        }
       
    </tbody>
</table>